AllCops:
  Exclude:
    - 'bin/*'

Layout/AlignHash:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Style/Documentation:
  Enabled: false
